version: "3.7"
services:
  choperas-service:
    image: choperas-rest:latest
    ports:
      - "8888:8888"
    volumes:
      - /opt/app
      - ./choperas-rest-config/config.json:/opt/app/config/config.json
    command: npm run start
    depends_on:
      - db

  mysql-database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=testpassword

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"