version: "3.9"
services:
  choperas-service:
    image: choperas-rest:latest
    ports:
      - "8888:8888"
    volumes:
      - /opt/app
    command: npm run start

  db:
    image: mysql:latest
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"